const T=[["jupiter","المشتري","Jupiter","🪐"],["saturn","زحل","Saturn","💍"],["neptune","نبتون","Neptune","🔵"],["uranus","أورانوس","Uranus","🩵"]];
let selected=null, member=null, admin=false;
const $=id=>document.getElementById(id);
async function api(url,opt={}){let r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt});let d=await r.json();if(!r.ok)throw Error(d.error||"حدث خطأ");return d}
function teamsHTML(){ $("teams").innerHTML=T.map(t=>`<div class="team ${selected===t[0]?"sel":""}" onclick="selected='${t[0]}';teamsHTML()"><div class="icon">${t[3]}</div><b>${t[1]}</b><small>${t[2]}</small></div>`).join("")}
function team(t){return T.find(x=>x[0]===t)}
async function join(){let name=$("name").value.trim();if(name.length<2||!selected){$("msg").textContent="اكتب اسمك واختار فريقك.";return}try{member=await api("/api/join",{method:"POST",body:JSON.stringify({name,team:selected})});localStorage.setItem("memberId",member.id);await showMember()}catch(e){$("msg").textContent=e.message}}
async function showMember(){if(!member)member=await api("/api/member/"+localStorage.getItem("memberId")); $("join").classList.add("hidden");$("admin").classList.add("hidden");$("member").classList.remove("hidden");let t=team(member.team);$("memberName").textContent=member.name;$("memberTeam").textContent=`فريق ${t[1]} • ${t[2]}`;$("memberIcon").textContent=t[3];await refreshMember()}
async function refreshMember(){let d=await api("/api/public");$("posts").innerHTML=d.posts.filter(p=>p.team==="all"||p.team===member.team).map(p=>`<article class="post"><small>${p.date}</small><h3>${esc(p.title)}</h3><p>${esc(p.body).replace(/\\n/g,"<br>")}</p></article>`).join("")||"<p>لا يوجد محتوى حاليًا.</p>";$("ranking").innerHTML=d.teams.sort((a,b)=>b.score-a.score).map((t,i)=>`<div class="rank"><span>#${i+1} ${t.icon} ${t.name}</span><b>⭐ ${t.score}</b></div>`).join("")}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
$("joinBtn").onclick=join;$("adminOpen").onclick=()=>$("loginModal").classList.remove("hidden");$("closeModal").onclick=()=>$("loginModal").classList.add("hidden");
$("loginBtn").onclick=async()=>{try{await api("/api/admin/login",{method:"POST",body:JSON.stringify({password:$("adminPass").value})});admin=true;$("loginModal").classList.add("hidden");$("join").classList.add("hidden");$("member").classList.add("hidden");$("admin").classList.remove("hidden");await refreshAdmin()}catch(e){$("loginMsg").textContent=e.message}};
async function refreshAdmin(){let d=await api("/api/admin");$("postTeam").innerHTML='<option value="all">كل الفرق</option>'+T.map(t=>`<option value="${t[0]}">${t[3]} ${t[1]}</option>`).join("");$("members").innerHTML=d.members.map(m=>{let t=team(m.team);return `<div class="member"><span>${t[3]} ${esc(m.name)}</span><small>${t[1]}</small></div>`}).join("")||"لا يوجد أعضاء";$("scores").innerHTML=d.teams.map(t=>`<div class="score"><span>${t.icon} ${t.name}: <b>${t.score}</b></span><button onclick="addScore('${t.id}')">+100</button></div>`).join("")}
$("postBtn").onclick=async()=>{try{await api("/api/admin/post",{method:"POST",body:JSON.stringify({title:$("postTitle").value,body:$("postBody").value,team:$("postTeam").value})});$("postTitle").value="";$("postBody").value="";await refreshAdmin();alert("تم النشر 🚀")}catch(e){alert(e.message)}};
async function addScore(id){await api("/api/admin/score",{method:"POST",body:JSON.stringify({team:id,amount:100})});refreshAdmin()}
$("logout").onclick=()=>{localStorage.removeItem("memberId");member=null;$("member").classList.add("hidden");$("join").classList.remove("hidden")};
$("adminLogout").onclick=()=>{$("admin").classList.add("hidden");$("join").classList.remove("hidden");admin=false};
teamsHTML(); if(localStorage.getItem("memberId")) showMember().catch(()=>localStorage.removeItem("memberId"));